# -*- coding: utf-8 -*-
"""
/***************************************************************************
 example2
                                 A QGIS plugin
 example2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-11
        copyright            : (C) 2024 by swapnil
        email                : swapnil
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def classFactory(iface):
    """Load Example2 class from example2 module."""
    from .example2 import Example2
    return Example2(iface)
